### ISSUE TITLE
Improve font rendering on Windows

### ISSUE THREAD

**Issue by bandit-masked** [EMATech/MidiExplorer#2]
Improve the font rendering for Windows specifically by using the following code.

```Python
import ctypes
# Include the following code before showing the viewport/calling `dearpygui.dearpygui.show_viewport` and set a bigger font size with DPG.
ctypes.windll.shcore.SetProcessDpiAwareness(2)
```

**Comment by bandit-masked** [comment]
![image](https://user-images.githubusercontent.com/96011344/187290526-189c1141-437a-42f7-8e7f-7e9ad29b7225.png)

**Comment by rdoursenaud** [comment]
I believe this doesn’t make any difference when using DearPyGui 2.0 as I do since 9a6518ff2d2e818fa22e27ad3d92ca780f4376d6.
Feel free to reopen if it’s still behaving poorly on you side.
